### ISSUE TITLE
Problems with dynamic file destinations 

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#1005]
Hey guys i am using the dynamic file destination api there are two options

```
 def saveAsTextFile(fileDestination: FileDestinations, suffix: String = ".txt")
                      (destinationFn: String => String): Future[Tap[String]]
```

and 

```
 def saveAsTextFile(destinations: DynamicDestinations[String, _, String],
                       windowedWrites: Boolean, numShards: Int)
    : Future[Tap[String]]
```

The issue is that both of these apis require the source collection to be of type String rather than T. 

I am using this api internally which i believe to be able to support more use cases

object Extensions {

  implicit class SCollectionExtensions[T](collection: SCollection[T]) extends Serializable {

    def saveAsTextFile2(emptryDestination: DefaultFilenamePolicy.Params,
                        elementToDestination: (T) => DefaultFilenamePolicy.Params,
                        serialiseElement: (T) => String,
                        windowedWrites: Boolean = true,
                        compression: Compression = Compression.GZIP,
                        shards: Int = 0,
                        transformName: String = "Save text files"): Future[Tap[T]] = {

      val outputFormatter = new SerializableFunction[T, String] {
        override def apply(input: T): String = {
          implicit val f = DefaultFormats
          serialiseElement(input)
        }
      }

      val outputFileNamePolicyMapping = new SerializableFunction[T, DefaultFilenamePolicy.Params] {
        override def apply(input: T): Params = {
          elementToDestination(input)
        }
      }

      val tempDir = FileSystems.matchNewResource(collection.context.options.getTempLocation, true)

      var outputTransform: TextIO.TypedWrite[T, Void] =
        TextIO
          .writeCustomType[T]()
          .withFormatFunction(outputFormatter)
          .withNumShards(shards)
          .withTempDirectory(tempDir)
          .withCompression(compression)

      if (windowedWrites) {
        outputTransform = outputTransform.withWindowedWrites()
      }

      collection.saveAsCustomOutput(transformName, outputTransform.to(outputFileNamePolicyMapping, emptryDestination))
    }
}

The benifits over the existing solution:

- Allows support for compression
- allows the user to provide any type T and a serialization fn

Would you consider a pr if i cleaned it up?

**Comment by nevillelyh** [comment]
We want to have a good trade of between covering majority of the use cases without making the API overly complex, in which case it might be better to just drop down to the native Java SDK like what you're doing here.

With that in mind, what about adding `compression` to `FileDestinations` that defaults to none, and an `trait OutputFormatter[T, O]`. We can then add an `(implicit of: OutputFormatter[T, String])` argument to the existing `saveAsTextFile` implementations. We should also add an default instance of `OutputFormatter[String, String]` for the basic case.

**Comment by nevillelyh** [comment]
The other question is, what's the downside of just using `saveAsCustomOutput`? Because that's supposed to solve these cases not covered by the convenience methods e.g. `saveAsTextFile`. If possible, I'd like to fix `saveAsCustomOutput` instead of playing catchup with upstream IOs and our wrappers.

**Comment by LukeDefeo** [comment]
Theres a few discussion points so lets take them in turn

1. I would argue that if scio is going to provide methods like dynamic save as text files it should be general purpose enough to suit most use cases. Right now since the upstream needs to be a string i would have serialize to a string upstream, and then in my recordToDestination function deserialize to figure out where it should go. This is pretty clunky unless I'm missing some other way? I think its a pretty common to have a SCollection[CaseClass] and have to write to a vertically partitioned structure in GCS 

2. Agree on defaulting compression to None is the right choice

3. I'm fairly new to scala so ill defer to your judgement on the use of implicit here. Sounds reasonable to me.

4. Im not too sure what you mean by fix saveAsCustomOutput. It doesn't seem to do much besides call the java api. How would it help in this situation?

**Comment by nevillelyh** [comment]
1.
It has something to do with different design approach between Java and Scala APIs.
In Java they use builder and can add arbitrary new flags via setters. The downside is obviously it's harder to maintain and use. In Scala, and in our case in particular, we want to have convenience methods like `saveAsTextFile` with 1 or 2 required arguments, and maybe a few more with default values. We don't want to add arbitrary number of arguments because
1. this may break backwards compatibility
1. method overloading doesn't play well with default arguments
1. we can't re-order args
1. methods with multiple `fn` arguments are harder to write fluently. We can write `.saveAs("path") { s => /* multi-line block */ }` for a single `fn` argument but it becomes clunky for multiple such args.

So among the dozens of settings a Beam IO typically allows, we only expose a few through Scio and have opinionated defaults for the rest. This should cover common use cases, esp. if the user wants something quick and easy. We're not trying to cover 80% of the available settings, more like cover 80% of the use cases by exposing 20% of the settings. And we don't want to play catch up with their ever changing IO designs.

Back to your question, we can add a 2nd `fn` argument but it'll break compatibility (not a huge deal) and make the API clunky (2 `fn` args). The implicit approach is slightly better but the user still needs to implement an `implicit val x = new OutputFormatter[...] {...}`.

4.
That's why I'm asking if you could just use `saveAsCustomOutput` instead. Very few I work with uses the dynamic destination, and when they do, it's almost always Avro records so you have access to the complete structured record in the `destinationFn`. So it feels like one of the 20% rare cases. Yes `saveAsCustomOutput` doesn't do anything besides the Java API but that gives you maximum flexibility. We can expose helpers (e.g. to implicitly make `SerializableFunction`, `DynamicDestinations` from scala `fn`s) to make Scala-Java interop easier. If we can make native Java IOs easy to use in Scio, `saveAsCustomOutput` should be a valid option here right?

**Comment by LukeDefeo** [comment]
Thanks for the clarification. Obviously we can carry on using saveAsTextOutput, I was just raising this as feedback that arose from out use case.

To clarify our use case is a heterogeneous pubsub topic of multiple event types that need to be dumped to gcs and big query.

**Comment by LukeDefeo** [comment]
Ill close this issue for now

**Comment by nevillelyh** [comment]
Added #1013 to track this. IMO it's more long term sustainable to make the Java IO more usable and reduce the boilerplate we have wrapping their options.
