### ISSUE TITLE
KryoException when changing case class and pipeline update

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#1021]
Hi

I have a trait and underlying case class that are emitted in a map stage of my pipeline. I have made changes to add a method to the trait and a constructor param to the class

After updating my pipeline i get:

```
 com.esotericsoftware.kryo.KryoException: Unable to find class: Cash
Serialization trace:
...
```

Cash isn't a class it looks like Kryo is a bit confused, I'm not too familiar with the internals of it. Anyway I can understand why this is broken, I require a new param to construct my object and there may have been instances of it serialized without this parameter so its not possible to decode.

One final thing, I do have a custom Kryo registrar and both the trait and case class are registered though I don't think that should make a difference.

My questions are:

1. Is my understanding of the problem correct?
2. What are the work arounds, the only one i can think of is to drain the pipeline and redeploy 
3. What changes to my traits/classes cause Kryo to be unable to decode my data

Any other advice / recommended reading on this topic would be appreciated as i imagine it is a somewhat common issue

**Comment by nevillelyh** [comment]
IIRC Kryo relies on having an argument-less default constructor to create a blank instance, and fills in the fields.

Can you try something like this:
```scala
class MyRecord(param: String) {
  def this() = this(null) // default ctor
}
```

Also this should've been caught in a test?

**Comment by LukeDefeo** [comment]
Not sure how i can write a unit test to reproduce this behavior, It didn't get caught in test pipelines as there way no data in flight in the pipeline so nothing to be decoded. Its not the end of the world as the pipeline isnt live

Ill try adding the ctor but not sure how that would help as none of my case classes have them. Even then the data was never serialized as Im adding a field so i will likely end up with a null value which isn't particularly good either. 

Have you not run into this issue while updating your pipelines internally?

**Comment by nevillelyh** [comment]
By default in unit test the `DirectRunner` will try to serialize elements in every stage to make sure they're ser/de- able.

Actually on 2nd thought it may have nothing to do with constructor signature, but the fact that the class changed and confused Kryo (it encodes the class type before content), hence the `Unable to find class: ��Cash` error. By changing the case class/trait, you might have changed the generated java class files.

Can't think of a decent way to do "update" without some very complex setup, because you have bytes serialized from old version and the new pipeline will want to deserialize them into the new incompatible type.

We've never run into this but we also avoid both "updating" pipelines and non-vanilla case classes.

**Comment by LukeDefeo** [comment]
It passes a your proposed test, my two separate pipelines were ser/de-able separately but not between their versions due to the incompatibility.

I think the way forward is for us to drain and redeploy jobs as opposed to data flows update mechanism.

**Comment by nevillelyh** [comment]
You're right, to properly reproduce this, we need to deserialize bytes of old version into new version of the class, which is not possible in the same JVM/test. Maybe we should document that clearly.
