### ISSUE TITLE
Issue with nested Avro records with same name

### ISSUE THREAD

**Issue by marcusb** [spotify/scio#1024]
After converting an Avro case class with toGenericRecord, the schema
of the resulting record becomes invalid if the original schema had
record fields with identical names (but different namespaces). It looks like
the namespace information is dropped in the conversion.

Failing test case here: https://github.com/spotify/scio/pull/1023

**Comment by nevillelyh** [comment]
So it seems this is re-building the schema from the generated case class, instead of reusing the one from top level. It's fixable but would require a lot of re-wiring by recursively passing the schema at every level.

https://github.com/spotify/scio/blob/master/scio-avro/src/main/scala/com/spotify/scio/avro/types/ConverterProvider.scala#L198

WIP branch: neville/dbg-1024
