### ISSUE TITLE
Validate that update of table would refresh schema

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1046]
While working with @fallonchen we have encountered a case where we had to update BQ table (which changed only the schema - the table name, and content stayed the same), after recompilation the change was not reflected in the case classes. It might be that the schema was reused from the cache. Validate if this is working-as-expected.

**Comment by nevillelyh** [comment]
Is this `@BigQueryType.fromTable("...")`? IIRC it only hashes table spec as cache key and doesn't check timestamp. Maybe that's why?

**Comment by jbx** [comment]
@ravwojdyla is this still something we need to look into?

**Comment by ravwojdyla** [comment]
Up to you really. It's probably a nice to have.

**Comment by nevillelyh** [comment]
So we use `Cache#withCachingKey` to cache schema (#1458) from `@BigQueryType.{fromQuery,fromTable}` but it doesn't check cache expiration or invalidation. To do that properly we'll have to make another (potentially multiple in the case of `fromQuery`) round trips to the service to check source table last modified timestamp. Not sure if it's worth the effort though.

To workaround, when developing locally, the user will have to `rm -rf .bigquery`, then `sbt clean compile` to rebuild. This shouldn't be an issue in CI since each build uses a fresh environment with no caching.

**Comment by nevillelyh** [comment]
Discussed IRL and this is not worth fixing. Closing.
