### ISSUE TITLE
Additional named step automatically added to the end of the pipeline

### ISSUE THREAD

**Issue by inejc** [spotify/scio#1061]
When `withName("BigQuerySink").saveAsTypedBigQuery(...)` transform is used as the last step of the pipeline, an additional step is automatically added at the end of the it. Inspecting the job through Dataflow UI gives named steps that look something like this:
```... --> BigQuerySink --> saveAsTypedBigQuery@{FileName.scala:82}1```

I asked on [gitter](https://gitter.im/spotify/scio) whether there is a way to name the **last** step as well and was asked to open an issue. I'm interested in doing so because every time the `withName("BigQuerySink").saveAsTypedBigQuery(...)` line is moved, the name of the **last** step changes and I end up having trouble updating the job on the fly.

**Comment by inejc** [comment]
I'm interested in looking into this.

**Comment by inejc** [comment]
Could you direct me to where I should start looking for the problem? I see that names are set to transforms in [PCollectionWrapper](https://github.com/spotify/scio/blob/d6635a626868c7db8926273c7c6c142883180ddb/scio-core/src/main/scala/com/spotify/scio/values/PCollectionWrapper.scala#L44) by calling `apply` on internal `org.apache.beam.sdk.values.PCollection`, getting the name from the [TransformNameable](https://github.com/spotify/scio/blob/d93b05d28e4a59695c3bb35f67c393458a43c94e/scio-core/src/main/scala/com/spotify/scio/values/TransformNameable.scala) trait.

**Comment by andrewsmartin** [comment]
@inejc That's right...so basically when you call `.withName()`, the `TransformNameProvider` is mutated so that it applies the given name to the **next** transform applied, after which the `CallsiteNameProvider` is used again. The `.saveAsTypedBigQuery` "transform" is actually composed of 2 transforms under the hood - first, a `map` to convert from case class to `TableRow`, then a `BigQueryIO.write` to write out the table rows. So here, `.withName` only sets the name for that first map, and then the default callsite naming scheme is used for the `BigQueryIO.write`. 

The easiest way to fix would be to prepend another `.withName` [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L1108), with something like `s"givenTfName$Write"`, where `givenTfName` can be obtained from `this`. Lmk if you have any questions!

**Comment by inejc** [comment]
Thanks for the help @andrewsmartin, opened a PR.

**Comment by inejc** [comment]
The initial problem is fixed, but the exactly the same problem now occurs one step before. The last two steps now look something like this: `saveAsTypedBigQuery@{FileName.scala:82}1 --> BigQuerySink$Write`. This probably happens because of [this](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L1126). I'm not sure whether this new behaviour was introduced with changes? cc @andrewsmartin

**Comment by inejc** [comment]
I agree--such behind-the-scenes mutations make it easier for errors to slip in. Anyway, I'd be glad to look into it and open a PR.

**Comment by inejc** [comment]
@andrewsmartin I've opened a PR (also tested the fix by submitting a dataflow-runner job and it looks alright). Could you explain why another name is not automatically set [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L1136)? Thanks.
