### ISSUE TITLE
I want to suppress writing to BigTable.

### ISSUE THREAD

**Issue by MikioSuematsu** [spotify/scio#1101]
There was a way to deal with the previous commit. #614 
However, at present, 'withRateLimit' seems to be gone.

How can I do the same?

**Comment by ravwojdyla** [comment]
@MikioSuematsu Since [bigtable-client-1.0.0-pre1](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/releases/tag/bigtable-client-1.0.0-pre1) should support client side throttling, #614 was a temporary workaround. Please check BigTable options including Bulk, Throttling. Another thing all together is #1057 (which might or might not be related to your issues), please follow the PR and the Beam issue ([BEAM-3311](https://issues.apache.org/jira/browse/BEAM-3311)) and please comment there. Will close this for now, please reopen if this comment doesn't help.

**Comment by MikioSuematsu** [comment]
@ravwojdyla 
I appreciate your kindness 😃 
I could do it by trying [enableBulkMutationThrottling](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/config/BulkOptions.java#L162)  and [setBulkMaxRequestSize](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/config/BulkOptions.java#L129) .
