### ISSUE TITLE
Create an example of using writeDynamic

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1164]
`FileIO#writeDynamic` comes up every now and then, would be good to have an example how to use it. It also seems like it's not very well documented in Beam itself. An example could be to write data per key to GCS with some smartish filenames.

**Comment by LukeDefeo** [comment]
```   
 def saveToFilesDynamic(collection: SCollection[JustDataEvent],
                               basePath: String,
                               shards: Int = 1,
                               compression: Compression = Compression.GZIP,
                               transformName: String = "Save text files"): Future[Tap[JustDataEvent]] =
        {
            val fileNaming = new SerializableFunction[DayPartition, Write.FileNaming]
            {
                override def apply(partition: DayPartition): Write.FileNaming =
                    (window: BoundedWindow, pane: PaneInfo, numShards: Int, shardIndex: Int, compression: Compression) =>
                        s"${Gcs.path(partition)}${window.toString}$shardIndex-of-$numShards.jsonl${compression.getSuggestedSuffix}"
            }

            val transform =
                FileIO
                    .writeDynamic[DayPartition, JustDataEvent]()
                    .to(basePath)
                    .by((input: JustDataEvent) => input.toDayPartition())
                    .via(Contextful.fn[JustDataEvent, String]((element: JustDataEvent) => compact(render(element.toJson()))), TextIO.sink())
                    .withNaming(fileNaming)
                    .withCompression(compression)
                    .withDestinationCoder(new DayPartitionCoder())
                    .withNumShards(shards)

            collection.saveAsCustomOutput(transformName, transform)
        }
    }
```

Here is a rough thing i cooked up. You need an intermediate type which defines a destination. A fn to go from the element type to this destination case class. You can also define exactly how it is named. Since we need to replicate sparks partitioning scheme of year=2018/month=10.. we encapsulate this in a case class and then in the name mapping for each destination we emit this path. Within the partition you can use the windows timings for the file name as i have done.

One issue you will face is that the intermediate type for partitioning, in my case the case class DayPartition will need to have a manually created coder. For some reason scios magic with avro atomic coder doesnt kick in. I dont know enough to comment as to why not, maybe @nevillelyh will be able to say
