### ISSUE TITLE
Add support for creating partitioned tables

### ISSUE THREAD

**Issue by oskoi** [spotify/scio#1167]
Now when creating a table using the method `saveAsTypedBigQuery`, it is not possible to specify the field by which to partition the table, the expiration time and the partition type using scio api. I propose to add an annotation that would allow it to be done, or add parameters to the `BigQueryType.toTable`. What do you think about this?

**Comment by nevillelyh** [comment]
This will probably be done outside of a job, i.e. creating the table with partition settings before running the job. Not sure about adding anything to `BigQueryType.toTable` since it's a macro and tricky to deal with.

I'd rather keep it simple and add methods to `BigQueryClient` for creating tables with partition settings. You want to give it a shot?

**Comment by oskoi** [comment]
Yeah, I'd like to do this.
