### ISSUE TITLE
Add Beam SQL integration + example

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#1177]
Probably but not limited to:
- Some mapping between `SCollection[T]` to a SQL collection that can be queried
- Mapping between `T` and Beam SQL row types
- Mapping between `T`'s schema and Beam's SQL schema

**Comment by brabster** [comment]
Hi,

I've been looking into how Beam has implemented SQL support. I'm not sure how we could do something clever like infer mappings to/from Beam's Row types. Here's an example:

```scala
val inSchema = Schema.Builder()...

def fooToRow(foo: Foo) = Row
  .withSchema(inSchema)
  .addValues(...from foo...)
  .build()

val outSchema = Schema.Builder()...

sc.avroFile[Foo](...)
  .map(fooToRow)
  .setCoder(inSchema.getRowCoder)
  .applyTransform(SqlTranform.query(...sql...))
  .setCoder(outSchema.getRowCoder)
  .saveAsWhatever()
```

There's nothing useful attached to the SqlTransform result to tell you how to code the output, and the mapping into the Row type is up to the user.

Are we looking for something that just makes that all a little neater and avoids dealing with the Coders directly... something like this (not sure what the methods should really be called, mind you)?

```scala
sc.avroFile[Foo](...)
  .mapToSqlRow(fooToRow, inSchema)
  .sqlQuery(sql, outSchema)
  .saveAsWhatever()
```

I could have a go at that - or if we're not sure what to do yet, I could write up some examples of Beam SQL with Scio if helpful?

**Comment by nevillelyh** [comment]
This will be a fairly big project if we want to approach it in a more holistic way.

- Most common types, e.g. Avro, Protobuf, BigQuery TableRow should be supported by Beam (schema and record bidirectional conversion) and they're in progress. But it'll take time.
- We need some macros to infer schema and converters for scala types e.g. case classes
- I agree that input type to Beam Schema/Row is more useful. For output, most cases we don't need to convert rows back to typed records and can just convert them to whatever generic records of the sink storage (BQ, generic Avro, etc., should be supported by Beam IOs).

**Comment by brabster** [comment]
I think macros and the like are little beyond the skills and time I have available :smile: but if it'd be useful to get docs/examples for how to use this stuff with Scio in the interim I could contribute that.

On the output types - I don't know if I was doing something wrong, but I couldn't even `saveAsTextFile` them without explicitly setting an output coder. I'm guessing that the result rows can't be passed around without it... so the inability to infer an output schema/coder seemed like it could be a pain. But I'm quite new to Beam so maybe I've just not understood things yet!

**Comment by jto** [comment]
The work we did on coders for `v0.7.0` should make supporting BeamSQL easier. 

Scio should be able to derive a `SchemaCoder` automatically for product types.  
As a bonus, we should be able to support Scala and Java collections out of the box, which will be hard / impossible in Beam because of erasure.

Assuming we do so, things like:

```scala
case class Foo(s: String, i: Int)
val rows: List[Foo] =  ???
sc.parallelize(rows)
   .sql("select s, sum(i) from PCOLLECTION group by s") // How do we infer the required Coder here ?
//...
```
should work out of the box.

Now the problem is that BeamSQL gives you back a `Row` which is really dynamic and does not play really well with coders . At this point the user **has to** provide a Coder explicitly for that `Row`.

Given that the SQL parsing is provided by calcite, we may be able to parse the query at compile time and infer a schema for it (assuming the SQL query is a stable value).

```scala
case class Foo(s: String, i: Int)
val rows: List[Foo] =  ???
sc.parallelize(rows)
   .sql("select s, sum(i) from PCOLLECTION group by s") // Parse the query using calcite in a macro and generate the SchemaCoder automatically.
//...
```

At this point we may be able to even generate a case class for the result of that query so that this:

```scala
sc.parallelize(rows)
  .sql("select s, sum(i) from PCOLLECTION group by s") 
```

would give you a  `SCollection[SomeType]` where `SomeType` looks like:

```scala
case class SomeType(s: String, `sum(i)`: Long)
```

The benefit being that you preserve typesafety.

poke @kanterov

**Comment by brabster** [comment]
Re: inferring a schema from Calcite. Beam contains examples of how to do it that might be helpful.

https://github.com/apache/beam/blob/9319ce18ac625b239c8cdc1b32e2b697d83c2504/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCalcRel.java#L80

https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/values/PCollection.java#L302

**Comment by nevillelyh** [comment]
Just curious, how would a query with multiple input tables work? `Query2[In1, In2, Out]`?

**Comment by jto** [comment]
So I gave this some more thoughts and I do agree with @kanterov, type inference should not depend on macro and work in IntelliJ.

I don't think the `Query` class should hold the coders bc. that's the `SCollection` job. 
Moreover, the `SCollection` will already hold a coder for its type. (A `SCollection[T]` has a `Coder[T]` already).

To apply a query on a `SCollection`, we need to satisfy 2 constraints:
- The "current" coder for the SCollection must be a `SchemaCoder`:
    ```scala
    val sc: SCollection[Foo] = ... // <- Coder[Foo] is known and selected already
    sc.sql(...) // Coder[Foo] needs to be a SchemaCoder
    ```
    This actually gives us polymorphism since the type of the `SCollection` on which the SQL query is applied needs only to be structurally compatible.
- The output type of the `Query` needs to have a `Coder`. This coder does not have to be a `SchemaCoder` (the query may simply return a scalar type).

So the signature of the SQL function would look something like:

```scala
def sql[A](query: String)(implicit sa: HasSchema[T], sb: Coder[A]): SCollection[A]
```

Where `HasSchema` is some from of evidence that the `SCollection` holds a `SchemaCoder`. (the exact way to for that constraint is to be decided. It may not even be an implicit).

This still allows "generic" queries that return `Row` but the user would have to provide a schema since AFAIK the only way to get a `Coder[Row]` is to provide the schema.

We could indeed provide validation ala doobie for the compatibility in tests. It may also be possible to completely check the query at compile time. For example:

```scala
val sc: SCollection[Foo] = ...
// Compile time query validation. Note it's an opt-in (tsql vs sql).
sc.tsql[Bar]("SELECT x, y FROM PCOLLECTION")
```

Not sure what @nevillelyh means by multiple input tables. Since you're running the query on an `SCollection` is that even possible ?
 
@regadas @kanterov wdyt ?
