### ISSUE TITLE
Make the repo work out of box with IntelliJ

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1199]
Some contributors are having trouble building the project because IT tests require GCP credentials for BigQuery and Avro files. Maybe we should configure sbt so that IT tests are not included by default in test sources?

**Comment by nevillelyh** [comment]
Related #1205 spotify/scio-idea-plugin#19

**Comment by mpasa** [comment]
I think this doesn't work if you have _wrong_ credentials. That is, credentials of your own project. 

It's a bit annoying in Intellij because it tries to build all the projects when you want to execute a test using the IDE. The only way I can get the IDE to build successfully is to ignore both `scio-avro/it` and `scio-bigquery/it` from the project structure.

The error I'm getting trying to execute a test in Intellij:
```scala
[error] scio/scio-avro/src/it/scala/com/spotify/scio/avro/types/AvroTypeIT.scala:64:4: exception during macro expansion: 
[error] java.lang.IllegalArgumentException: requirement failed: Unable to match Avro file from path 'gs://data-integration-test-eu/avro-integration-test/folder-a/folder-b/shakespeare.avro'
```
