### ISSUE TITLE
Make randomSplit accept a random gen

### ISSUE THREAD

**Issue by martinbomio** [spotify/scio#1229]
Would be nice to be able to pass a seed or a (possible seeded) random generator to all variations of `randomSplit` (https://github.com/spotify/scio/blob/72f8a9dcccc1a484f4f6d81678c21ca7cd670c42/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L459)
This will make tests deterministic when using this transform.

**Comment by jto** [comment]
Given that `ThreadLocalRandom` does not support seed (https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadLocalRandom.html#setSeed(long)) , it's not possible in the current implementation. @nevillelyh do you think we can replace `ThreadLocalRandom` by a standard `Random` so that we can set a seed ?

**Comment by nevillelyh** [comment]
I agree. Also unlike spark which has fixed # of partitions and ordered items within each partition, Beam has no such notion since it's runner dependent. So we can't really assign seeds deterministically to each partition and random numbers to each element.

I'm leaning towards closing this as a "won't fix".

**Comment by martinbomio** [comment]
@nevillelyh One alternative is to has the input and split based on the hash if sc.isTest, with the right hash function, this will make the splits deterministic, at least for testing, which was my initial use case.

**Comment by nevillelyh** [comment]
Hashing will break the weight distribution though since the underlying elements may hash unevenly.
