### ISSUE TITLE
Revisit scala 2.12 issues

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1275]
[SPARK-14220](https://issues.apache.org/jira/browse/SPARK-14220) (scala 2.12 support) was finally closed. We should look into it and see if there's any improvements or fixes we can adopt for scio.

**Comment by jto** [comment]
Flink's support is still WIP: https://issues.apache.org/jira/browse/FLINK-5005

**Comment by jto** [comment]
I'm looking into this and it seems to me the only thing we need to do is to use the last version of ClosureCleaner from Spark. Is there anything else ?

My only concern is that we basically have no way to check that scio + Scala 2.12 _actually_ works.
I've tried running the test suite of a couple of pipelines after bumping the Scala version from 2.11 to 2.12 and all the tests are green... 

Scala 2.13 should also be released in a few weeks so it'd be good to have a way to make sure nothing is broken.

**Comment by andrewsmartin** [comment]
+1 on using the latest ClosureCleaner changes, the one in Scio currently does nothing for 2.12 due to treatment of lambdas. https://github.com/apache/spark/pull/21930. That said I don't know of any failure scenarios where the compiler isn't good enough but we can probably find some by looking at newer test cases in Spark.

**Comment by mewppis** [comment]
We've been running 2.12 since 0.7.0 and it works fine. Closing this
