### ISSUE TITLE
tensorflow: sequenceExamples

### ISSUE THREAD

**Issue by ckchow** [spotify/scio#1659]
I've been able to write / read SequenceExamples to / from TFRecords in the same way that regular Examples currently are handled. It would be nice to have library support for both IO and prediction with SequenceExamples.

**Comment by regadas** [comment]
@andrewsmartin @brianmartin Do you have any thoughts on this?

**Comment by brianmartin** [comment]
Yes. @andrewsmartin and I actually just heard from a few internal customers this week that this feature would be useful. I was actually considering picking this up. Let me touch base with @andrewsmartin offline and I'll post an update here.

**Comment by brianmartin** [comment]
Looks fairly straightforward to implement. The implicits for a `SCollection[SequenceExample]` should look very close to the existing ones for `SCollection[Example]`. 

The only slight wrinkle is that `SCollection[Seq[Example]]` is automatically merged into `SCollection[Example]`. But that still seems reasonable because if you actually want `SequenceExample`, which would be somewhat rare, then you would explicitly create a `SCollection[SequenceExample]`.

I haven't investigated whether the existing predict function would work as is, but.. should be possible.

@ckchow Were you interested in producing a PR? :)

**Comment by ckchow** [comment]
I have an implementation that is working. wouldn't mind tidying it up and submitting it when a little less busy.

**Comment by brianmartin** [comment]
Awesome. That'd be most welcome @ckchow!

**Comment by jbx** [comment]
@ckchow - did you have a chance to look at this?

**Comment by brianmartin** [comment]
This is awesome @martinbomio! We had, here on ml-infra, been considering adding this but it was perpetually stuck in the backlog.

(cc @ckchow: I'm assuming PR #1757 satisfies your use case as well?)

**Comment by brianmartin** [comment]
I think we're all good here, right @regadas?

**Comment by regadas** [comment]
@brianmartin yup, we can close this.
