### ISSUE TITLE
Use Row Schema to reduce Shuffle in Shuffle-Joins 

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1954]
A very common approach for joining SCollections is as follows:
```scala
left
 .keyBy(_.userId)
 .join(right.keyBy(_.userId)
 .values
 .map{
    case (l, r) =>
  }
```

This is because data read in pipelines are not naturally stored as KV pairs, but as V only.

This leads to shuffling very wide records, which shuffles the common `K` twice (in the left as well as the right side) - more for multi joins

For example, If the size of `V` is 5.32GB, after `keyBy` this becomes 7.17GB, or ~ 35% more data to shuffle.

If the Schema is known, this can shuffle can be reduced:
```
left.
  join(right, on"$left.userId = $right.userId) 
```
The restriction is that the `keyBy` doesn't take an arbitrary function, but a sub schema of the original schema.

This also opens up expression based joins, eg: efficient range joins, with bucketing and without the need to do a partial cross join.

We can have a scalafix to replace the above trees with something like this, providing a quick way to reduce shuffle.

Current problems:
I tried to write a query as follows:

```scala
sql"SELECT (s.userId, s.userIdLong, s.fields) AS _1, (a.artistId, a.artistIdLong, a.artistName, a.fields) AS _2 FROM $s a INNER JOIN $a a ON s.userId = a.artistId"
.as[(User, Artist))]
```
where `User` and `Artist` are case classes.

This gets stuck because:
`Schema[(User, Artist)]` takes the labels as `_1` and `_2` however BeamSql produces a schema which is something like `_1$$...`

I think Scala tuples to Beam SQL rows mapping should be consistent / not sure how to query `as[Tuple2[A, B]]` in scala.

I discussed about this briefly with @jto yesterday.

**Comment by regadas** [comment]
Hi @anish749, If I understood this correctly, this all comes down to reducing the size of `V` before the join actually happens.

Regarding your first case, I'm not sure about the mixed semantics here, I would actually prefer to have a way (which we already but still experimental) to convert from `BiggerV` to `SmallerV` and since `keyBy` is basically `map(t => (f(), t)))` this is easily achievable. Using `SQL` is the other way of achieving this.

Regarding your second example, unfortunately this doesn't work out of the box at the moment. We will need to investigate.
Also from what I can see in BeamSQL in joins, values `V` are kept with the same input schema meaning you also need to apply the sub schema before doing the join.

**Comment by anish749** [comment]
Thanks for checking this.
I think if we have a way to go from `BiggerV` to `SmallerV` it would be very helpful, in reducing shuffle. This was my original intent. Can you point me to the experimental thing we have. I would love to try that out.

I was trying with SQL, but if we can do without SQL it would be super awesome.

**Comment by regadas** [comment]
@anish749 I was talking about [this](https://github.com/spotify/scio/blob/master/scio-test/src/test/scala/com/spotify/scio/sql/BeamSQLTest.scala#L532)

Closing this for now
