### ISSUE TITLE
Sequential processing with FileIO

### ISSUE THREAD

**Issue by marrrcin** [spotify/scio#1958]
I want to achieve sequential processing of some data - let's say I have list of GCS buckets with files to process. I cannot read from all of those buckets at once, because it will put too much pressure on the dependent service I call during processing. List of buckets is know when the pipeline starts, so my idea was to somehow generate the pipeline in loop, in which I will make every next part of a pipeline depend on the outputs of the previous one (just for the sake of synchronization). The problem is, that `FileIO` outputs `Future[Tap[<my type]]` and I would like to consume it without scheduling new pipelines like in the `Taps` example in Scio repo.

The reason I want to do this is because I don't want to initialize new DataFlow job for every bucket (the overhead of spinning up the jobs is orders of magnitude slower than the processing itself for some buckets).

So the general question is: how to create sequential pipelines with intermediate IO?

**Comment by anish749** [comment]
Ideally in MR / Data flow /Beam model, you would not want to do synchronisation/sequencing yourself. Dataflow/Beam model is designed for processing that can be parallelised well. Beam creates a dag based on the logic you define and does a topological traversal of that dag and executes the transforms. So if you have `n` inputs which can be processed in parallel, Beam / Dataflow would do so by design. Once a pipeline is defined, it has a known number of inputs and outputs. Sequencing is done based on the output data of one transform being a dependency of another transform. Loops are always discouraged in this pattern. 

If you have a dependent service which you want to rate limit, an easy fix would be to cap the number of workers, and hence the vCPUs used in the dataflow job. Ideally with autoscaling Dataflow should not go on increasing the vCPU counts because downstream services can be slow (from my exp, it tries but eventually brings down the workers). If you want to rate limit things further (say process 1 element and sleep for 10s), you might be interested in [stateful processing](https://beam.apache.org/blog/2017/02/13/stateful-processing.html)

**Comment by regadas** [comment]
I recommend you having look at https://beam.apache.org/documentation/execution-model/. And then probably https://beam.apache.org/documentation/programming-guide/

The gist is **don't** do synchronization inside beam transforms! 

In regards to `Future[Tap[<my type]]` this semantic is being deprecated so don't rely on it!

To control the data processing speed to avoid congestion in the sinks it's sometimes tricky. In addition to the number of workers and instance types, depending on the type of sink you can explore strategies like windowing, sharding, buckets and backoff policies.

**Comment by marrrcin** [comment]
Thanks guys!
