### ISSUE TITLE
pubsubSubscriptionWithAttributes does respect 'withName'

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#1970]
If I create the following and run it in dataflow

```
context
      .withName("read from test blah")
      .pubsubSubscription[String]("projects/not-exist/subscriptions/not-exist1")
      .withName("mapper1").map(x => x)

    context
      .withName("read from test2 blah")
      .pubsubSubscriptionWithAttributes[String]("projects/not-exist/subscriptions/not-exist2")
      .withName("mapper1").map(x => x)

```

I get this:

![image](https://user-images.githubusercontent.com/2492575/59357217-579fb680-8d22-11e9-8d1c-5e1e859d1cf2.png)

The pubsubSubscriptionWithAttributes step inserts an extra step but its same isn't derived from the proceeding withName. The full name is:

`pubsubSubscriptionWithAttributes@{StreamToFdlJob.scala:127}2
`

The issue is it has the line of source code in it which makes job updates tricky. 

Ideally, it should take my earlier step name and then append something like 'map attributes' or whatever this step is actually doing.

**Comment by ClaireMcGinty** [comment]
@nevillelyh this could be solvable by wrapping [these two transforms](https://github.com/spotify/scio/blob/ff28189674f0f08b17665d08e1b16dec10336e10/scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala#L181) into a single, expandable `PTransform[PBegin, PCollection[WithAttributeMap]]`, which is what `.withName()` would then be applied to.  Not 100% sure if that would solve the streaming job update problem, needs to be tested. wdyt?

**Comment by nevillelyh** [comment]
Yeah looks like it. @LukeDefeo can you try the suggested idea, e.g. replace `sc.applyInternal(r)).map` with a composite `PTransform`?

**Comment by ClaireMcGinty** [comment]
I verified that the above solution works with respect to updates! I can submit a PR, but this issue does raise some larger questions, since I'm sure there are other Scio transforms that internally wrap > 1 `PTransform`s (for example, it looks like all of Scio's PubsubIO writes use two transforms)... should we try to enforce that 1 Scio transform should always => 1 top-level `PTransform`?

**Comment by nevillelyh** [comment]
In theory yes we should enforce. But it's hard to do programmatically? In that case we have to catch & fix case by case.

**Comment by ClaireMcGinty** [comment]
Cool. In this case I think we need to fix it for both `PubsubIOWithAttributes` and `PubsubIOWithoutAttributes`. The reason @LukeDefeo is only seeing this issue with `pubsubSubscriptionWithAttributes` is because the parameterized type of the example is `String`. Beam's `PubsubIO` only supports attributes for type `PubsubMessage` input. So `.pubsubSubscription[String]("...")` directly delegates to `beam.PubsubIO.readStrings()` , whereas `.pubsubSubscriptionWithAttributes[String]("...")` has to use `beam.PubsubIO.readMessagesWithAttributes()` and then do an extra transform step to convert the message payload to `String` and decode the attributes. I think you'd see the same behavior (i.e. adding an extra step) calling `.pubsubSubscription[SomeCaseClass]("...")`because it also has to do an extra conversion from payload bytes => `SomeCaseClass`.

**Comment by ClaireMcGinty** [comment]
\+ if https://github.com/apache/beam/pull/8879 gets approved we can eliminate the extra map entirely :) (and optimize the case of `pubsubSubscriptionWithAttributes[PubsubMessage]` since we wouldn't deserializing the same bytes twice)

**Comment by LukeDefeo** [comment]
We've done some more testing and this wasnt the issue with our job update. It was something, will raise another issue. I imagine the update would still fail though if

**Comment by LukeDefeo** [comment]
That looks good.

**Comment by ClaireMcGinty** [comment]
We can close in favor of #1994.
