### ISSUE TITLE
Bloom Filter and other side input size may exceed default cache

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2040]
`sparseIntersectByKey` and a few other transforms that rely on Bloom Filter or side input may create side input greater than the default 100MB cache. Should we warn this, automatically bump cache, or something else? However cache size is not exposed to us and runner specific.

What about:
- warn if SI size estimate is > 100MB
- document size consideration

That's probably the best we can do without involving runner specific logic.

Optimal BF setting is computed here:
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala#L38

**Comment by anish749** [comment]
It is very hard to understand the actual size the `BloomFilter` takes. When relying on the estimated size shown in DF UI, I have a feeling it shows the serialized size. IIRC the size is calculated by serializing to a `CountingOutputStream`. Again I am not sure I am remembering correctly, but I think Kryo Serialization on Algebird's BF (depending on the actual instance) can have a very high foot print and the dataflow UI can be misleading.

I have not seen the optimal BF setting give a value of more than 125 MB for 1 Bloom Filter.  
With n BloomFilters I would expect Dataflow to distribute properly in a way so that more than 1 of n partitions of the PCollections are not in 1 woker. I haven't tested this distribution though. In this case the assumption from Dataflow is that we don't have more than 1 BloomFilter in 1 worker.

Eg: As of now I can find one usage of `sparseIntersectByKey` which might possibly exceed this 100 MB limit. Here is a [run](https://console.cloud.google.com/dataflow/jobsDetail/locations/europe-west1/jobs/2019-07-09_22_22_05-15855312643878654379), it shows the Side Input Size as 348MB, (Based on the num keys it should not be 348 though, so I'm blaming Kryo and assuming this is the serialized size) It also has no extra setting for Worker Memory. And Bytes Read from Side Input is 357GB(?). I am not sure how to read this these two metric and if I understand them correctly.

Another thing to consider is that the side inputs are stored as weak references, and I would assume it to not be garbage collected if running on high-mem instances, which the referenced job is, hence the worker memory limit isn't causing a problem (?)

I had thought of modifying the Optimal BF settings calculation in a way that 1 BF is always less than 100MB, but that would introduce runner specific logic.

One option would be before job submission, if the job uses DataflowRunner, we can check if the `workerCacheMB` is not set, and we can use this to automatically bump up the `workerMemoryCache` if needed. (Probably have a way to allow inserting runner specific logic with `context.close()` )

**Comment by nevillelyh** [comment]
As you said it's hard to estimate size (unless if we move to something more deterministic, like a mutable Java impl backed by a raw bitset) so setting `workerCacheMB` may not always work, plus it's runner specific. For things that we can't reliably fix in the library, I prefer to have some warning and documentation, and rely on users to tweak case by case.

**Comment by anish749** [comment]
I was thinking about this a bit.
1 - Have a mutable store where any transform can log estimates during pipeline construction (maintained somewhere in the `ScioContext` class).

Based on the runner, warn if the estimate needs a separate setting that is not set correctly. But it requires something like [this](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L76-L77)
I am not sure how to avoid this.

OR 
2 - keep things simple and just add a warning log [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala#L38) with runner specific things or a link to a doc on how to fix / best practices.

WDYT?

**Comment by nevillelyh** [comment]
Prefer #2, keep it simple for now.
