### ISSUE TITLE
Add support for dynamically supplying rowRestrictions for BigQuery Storage API

### ISSUE THREAD

**Issue by drachenbach** [spotify/scio#2061]
Currently, `rowRestriction`s can only be supplied statically in`@BigQueryType.fromStorage`. It would be great if `rowRestriction`s could be passed dynamically. E.g., a specific column value could be set depending on command line arguments.

**Comment by nevillelyh** [comment]
We have this method on `ScioContext` right now which works for all three of `from{Table/Query/Storage}` and `newSource` is used to override table or query.

`def typedBigQuery[T <: HasAnnotation: ClassTag: TypeTag: Coder](newSource: String = null)`

Not sure `rowRestriction` fits here though since it's specific to storage. Add a new method? Name?
@regadas opinion?

**Comment by regadas** [comment]
@nevillelyh I think adding a `typedStorage` might be ok, however there's another solution perhaps? if this flexibility is need couldn't we just use:

```scala
import com.spotify.scio.bigquery.BigQueryTyped._
val sc: ScioContext = ???
val table: Table = ???
val params = Storage.ReadParam(fields, rowRestriction)

sc.read(Storage(table)(params))
```

tbh i think i prefer this then adding a new method? wdyt?
