### ISSUE TITLE
Can't test writing to the same table multiple times in the same Pipeline.

### ISSUE THREAD

**Issue by randyunger** [spotify/scio#2128]
https://github.com/spotify/scio/blob/d77955220ae18f53e178b329b836f16bb74d1134/scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala#L91

Scio doesn't prevent me from writing to the same table multiple times in the same pipeline. Why have a test platform that is more restrictive than the framework?

**Comment by nevillelyh** [comment]
IIRC Beam's `BigQueryIO` doesn't enforce this but the underlying runner might during job submission. Also writing to the same table with conflicting `{Create,Write}Disposition`, e.g. TRUNCATE vs APPEND may lead to bugs. This is just an extra precaution against possible issues.

**Comment by tritium6** [comment]
1) If there are use cases that Scio intentionally actively prevents, then those should be prevented at compile time or run time. It doesn't make sense to allow this type of usage at runtime but prevent it in testing. From a user's perspective, I've got my pipeline working how I want and I'm ready to write some tests to make sure it stays that way, but I'm being told the test framework has a reduced feature set compared to the run time framework, so essentially I'm being steered away from implementing tests, which doesn't seem like the practice Scio would want to enforce. If the argument is that Scio is intentionally preventing what I'm trying to do, then it should prevent me from doing it at compile time or run time, not just in testing.

2) This should be a usage that Scio allows, not prevents. Why would Scio disallow all instances of multiple writes just because some instances of multiple writes may not be valid? In fact, my use case is supported by the underlying runner and does not have conflicting write dispositions. More reasonable would be to allow the valid use cases and disallow the invalid ones. Rather than preventing possible issues, the issue in this case is the unnecessary prevention of a working use case put in place by the testing framework.

**Comment by randyunger** [comment]
If there are use cases that Scio intentionally actively prevents, then those should be prevented at compile time or run time. It doesn't make sense to allow this type of usage at runtime but prevent it in testing. From a user's perspective, I've got my pipeline working how I want and I'm ready to write some tests to make sure it stays that way, but I'm being told the test framework has a reduced feature set compared to the run time framework, so essentially I'm being steered away from implementing tests, which doesn't seem like the practice Scio would want to enforce. If the argument is that Scio is intentionally preventing what I'm trying to do, then it should prevent me from doing it at compile time or run time, not just in testing.

This should be a usage that Scio allows, not prevents. Why would Scio disallow all instances of multiple writes just because some instances of multiple writes may not be valid? In fact, my use case is supported by the underlying runner and does not have conflicting write dispositions. More reasonable would be to allow the valid use cases and disallow the invalid ones. Rather than preventing possible issues, the issue in this case is the unnecessary prevention of a working use case put in place by the testing framework.

**Comment by nevillelyh** [comment]
Not all checks can be done at compile time or run time. And Scio's goal is not to support all possible use cases, but to provide an opinionated way to make common things simple.

You

**Comment by nevillelyh** [comment]
Butterfingered. Feel free to re-open if you can provide more details or propose a solution.
