### ISSUE TITLE
Switch to Avro based BQ loads

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2341]
https://github.com/apache/beam/pull/9665

There's a PR upstream to write Avro instead of JSON files for BigQuery load.

**Comment by nevillelyh** [comment]
Upstream is merged, should be available in Beam 2.18.0.

**Comment by regadas** [comment]
Initial support can be found here https://github.com/regadas/scio/tree/feature/bt-avro-write 

Currently blocked on this fix https://github.com/apache/beam/pull/10869

Also note that BigQuery does not support DateTime type with Avro https://issuetracker.google.com/issues/140681683

**Comment by jto** [comment]
Upstream issue has been fixed by a PR merged in March it should work with Beam >= 2.20.
Scio has diverged quite a bit from your original branch @regadas. Seems like it's time to revive it :)

On a side note, do we have any estimate of the potential performance gain ?

**Comment by regadas** [comment]
@jto yup it's on my todo list. 

I haven't run benchmarks myself (yet) but in theory and from the numbers provided in apache/beam#9665 it looks promising.

Regarding the `Datetime`, according to the issue there's still plan to add full support but no idea about timeline, so for the time being I guess this will need to be explicit user code. If we play this right, once the support is there we can make it the default impl.

**Comment by jto** [comment]
Those number looks goooood!

I looked a the code of your branch. Everything looks good to me except I would not make `Format`a typeclass bc. it breaks type inference while not providing any value since the user can't add their own implementation. 

I'd make it a param with a default value. The default value would be neither `Avro` or `TableRow` but litteraly `Default` so that we can switch to `Avro` once `Datetime` is properly supported.
