### ISSUE TITLE
TFRecordIO is uncompressed by default

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2344]
https://github.com/spotify/scio/blob/master/scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala#L54

TFRecord files with TF `Example` records are inefficient due to the denormalized field name strings.
Should we compress by default?

@andrewsmartin do you remember why this was the default?

**Comment by andrewsmartin** [comment]
I don't remember, I vaguely recall @regadas having some opinions but may have been a different issue. +1 from me on compressing by default, should save a ton of space and the TF(X) tools all work out of the box on compressed tfrecord files.

**Comment by regadas** [comment]
I think last there was a bug because the compression was not consistent across the stack! and some of them did not had compression type detection; Given that this happened and can happen from API perspective not making compression assumption might be the best way to go about it;

Also, this behavior is consistent with some other IO's i.e TextIO, BinaryIO, BigQueryIO, etc

**Comment by nevillelyh** [comment]
Yeah with the exception of AvroIO, but I guess because Avro compression is handled in its library instead of File IO streams so that's a different story.

**Comment by nevillelyh** [comment]
Also do you remember what the bug was?

**Comment by regadas** [comment]
Unfortunatly I don't recall exactly the bug only that it was along those lines.

**Comment by regadas** [comment]
@nevillelyh I think we keep it as is; Can we close this?

**Comment by regadas** [comment]
@nevillelyh ^^
