### ISSUE TITLE
Clean up side input related API

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2353]
We seem to have a lot of different ways to do side input now, including scala collection backed `SideSet/SideMap`, and the new `.map` method on built-in `SideInput`s and sparkey based ones. On top of these we also have the singleton/list/map side input that're thin wrappers over Beam ones but some might have performance issues.

https://github.com/spotify/scio/commit/fa4cbedb38d199b6ffdb4b288ca3f48c91c70fdf
https://github.com/spotify/scio/pull/2287

From an API ergonomic point of view it'd be nice to provide a few proven choices. Maybe it's time to review all these options?

@psobot @sisidra

**Comment by nevillelyh** [comment]
Right now we have

1. `SCollection[T]#asSingletonSideInput`
1. `SCollection[T]#asIterableSideInput`
1. `SCollection[T]#asListSideInput`
1. `SCollection[T]#toSideSet`
1. `SCollection[(K, V)]#asMapSideInput`
1. `SCollection[(K, V)]#asMultiMapSideInput`
1. `SCollection[(K, V)]#toSideMap`

1, 2, 3, 5, 6 wraps Beam `View`s directly. According to the docs, 2 is not required to fit in memory while 5, 6 might fallback to disk cache and slow in some cases (need benchmark). 4 & 7 has inconsistent name & type signature and 7 returns mutable `Map` and `ArrayBuffer`.

What about deprecating 4 & 7, creating `asSetSingletonSideInput`, `asMapSingletonSideInput`, and `asMultiMapSingletonSideInput` instead? `Singleton` in the name signals that they're guaranteed to fit in RAM, and we can future cleanup/optimize by using mutable collections when constructing the SI and exposing only the immutable interface. A side benefit is we can recommend `as*SingletonSideInput` for performance reasons as they're all guaranteed to fit in RAM.

**Comment by anish749** [comment]
4 and 7 follow a different naming and can be deprecated.

`asSetSingletonSideInput` would be needed to replace `SideSet`.

However `asMapSingletonSideInput` and `asMapSideInput` are both one element PCollectionViews and appears to be logically the same thing. Also `asMultiMapSideInput` and `asMultiMapSingletonSideInput` also result in one element collection.

We can choose to provide overloaded `hashJoin[W: Coder](thatSide: SideInput[Map[K, Iterable[W]]])` as a replacement for `SideMap`, since `SideMap` is just a wrapper over `SideInput`, and users are always accessing the public SideInput to do anything. Also it offers mutable APIs which can be dangerous if someone starts modifying the Maps in the SideInputs)
