### ISSUE TITLE
Non primitive keys result in incorrect sparse transforms for more than 125M sparse keys

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2450]
For cases when the smaller side of the sparse transforms have more than 125M keys, we partition the data and use multiple BloomFilters. This partitioning logic relies on Java's `.hashCode()` on the Key of the Pair SCollection.

Java's `.hashCode()` is non deterministic (in its API) and returns non primitive types (arrays and tuples).

Hence sparse do not work for arrays and tuples + more than 125M keys.

It is fairly easy for the user to make this mistake :(

**Comment by nevillelyh** [comment]
> returns non primitive types (arrays and tuples)
Can you clarify? `hashCode` returns `Int`, a primitive.

**Comment by anish749** [comment]
It depends on the JVM, so different JVMs would produce different values.
If I try 
`val hash = ("a", "b").hashCode`
on different scala shells on the same machine, I would most likely get same values (because we are on the same processor (or something)). On the same instance of the JVM it is guaranteed and consistent.

If I try this on different JVMs (on different machines), I will get different values. 
Here is an example from my local machine and `scalafiddle.io`.
<img width="1147" alt="Screenshot 2020-02-11 at 12 08 03" src="https://user-images.githubusercontent.com/15274312/74215633-b3fb1180-4cc7-11ea-8777-a3f5de2ef5bd.png">

I believe this would be a problem in distributed processing as it involves different machines.

Of course with Arrays, this problem can be reproduced on the same instance of the JVM itself. 
```scala
scala> Array(1, 2).hashCode
res1: Int = 373682836

scala> Array(1, 2).hashCode
res2: Int = 510207317
```

`case class` behaves same as tuples.
<img width="718" alt="Screenshot 2020-02-11 at 12 16 08" src="https://user-images.githubusercontent.com/15274312/74215807-60d58e80-4cc8-11ea-9489-27bc48fafe12.png">

**Comment by regadas** [comment]
Hi @anish749 I was looking at this and i believe that this is almost a non issue. Most of the `hashCode` for primitive, collections and case class'es are consistent accross same/different `JVM` beeing `Array` the only exception. The reason you were getting different hashCode was because you were mixing scala versions.

We can however change from `hashCode` to `##` and probably had a consistent `hashCode` when `K <:< Array[T]`; this is doable by using `Arrays.hashCode` instead.

OTOH, we could probably just use guava `Funnel` here as well, but would require users to add an extra import. (doesn't seem appealing tbh)
