### ISSUE TITLE
Add Scio binding for Beam's `SortValues` transform

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#2530]
https://github.com/apache/beam/blob/master/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/SortValues.java

Possibly we could include the preceding Beam `GroupByKey` transform as well so the signature of the Scio method looks more like `topByKey` and users don't get confused trying to use Scio's `.groupBy` method with it, and fix the Coder specifically as a Beam `KvCoder`.

**Comment by nevillelyh** [comment]
If we follow the `SortValues` interface, it should probably be:
`SCollection[(K1, (K2, V))]#sortByKey: SCollection[(K1, Iterable[(K2, V)])]`.

Or do we want to mimic the Scio ones instead?
`SCollection[(K, V)]#sortByKey[K2](ord: V => SK): SCollection[(K, Iterable[V])]`

The 2nd feels more idiomatic Scio. Another question is how to we ensure this is not misused in place of `topByKey`?

**Comment by ClaireMcGinty** [comment]
I agree, the second one feels more consistent with the rest of the Scio API, although users may be confused anyway we don't support an implicit `Ordering[V]` as argument.

Not sure how to guard against misuse--putting it in a separate module seems like overkill, maybe the best we can do is good documentation/maybe logging a warning.

**Comment by nevillelyh** [comment]
Brought up in internal discussion. `SortValues` doesn't support descending, and lexicographical comparator won't work for types like double. I wonder if there're ways to work around this. We might have to fork the `NativeFileSorter` though?

**Comment by nevillelyh** [comment]
https://issues.apache.org/jira/browse/BEAM-8985
https://issues.apache.org/jira/browse/BEAM-8986
https://issues.apache.org/jira/browse/BEAM-8987

**Comment by regadas** [comment]
Yeah interesting points. If we tackle those I think we can try fix it upstream instead of forking?

Nevertheless, I think we can still provide the api (with some caveats) since it still helps with the `Coder` and `KV` juggling.

**Comment by nevillelyh** [comment]
Would be nice to at least fix the lexicographical sorting issue w.r.t. numbers, otherwise users might get incorrect result by mistake.

**Comment by regadas** [comment]
Trying to get a working example where I can repro that issue

**Comment by ClaireMcGinty** [comment]
Yeah I think users might not make the connection that the Coders that they're used to using just for ser/de are also responsible for the sorted bytes representation. Are there any cases where the user would want one Coder for ser/de and a different one for sorting?

**Comment by regadas** [comment]
@ClaireMcGinty that's a good point TBH I don't think coders should be used for more purposes other then being efficient at ser/de.

**Comment by regadas** [comment]
So I had a first deeper look into the external sort and it might be somewhat sound even for signed numerical types. Right now I'm short on time but I'll expand this later ... either here or IRL. /cc @nevillelyh @ClaireMcGinty

**Comment by nevillelyh** [comment]
Looking at [`SortValuesDoFn`](
https://github.com/apache/beam/blob/master/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/SortValues.java#L127), raw, un-encoded objects are going through the `DoFn`. They're only encoded before being fed into the external sorter, presumably because the original Hadoop `SequenceFile` based sorter can only sort bytes out of the box. There isn't a performance reason to sort bytes instead of raw objects.

So it seems to support what we want, i.e. custom ordering, ASC/DESC options, we'll have to redo the entire `SortValues` & `NativeSorter`, and push the coders & `Ordering` further into `NativeSorter`. Make sense?

**Comment by regadas** [comment]
Totally forgot to update this 🤦‍♂ ... After experimenting a bit in #2542 I went down the rabbit hole🐰 

 `SortValues` documentation says that keys are sorted lexicographically which is correct but incomplete. Lexicographical order is only happens if the keys are encoded as `String`; numeric keys will be sorted differently and don't follow the normal numeric order. The reason lies on how numeric values are encoded in the JVM; Signed values are represented between -127 to 128 and unsiged between 0 and 255; negative values are prefixed and Floats are converted to ints and Doubles converted to Longs. `NativeSorter` uses unsiged byte comparison ... can't recall hadoop but it's easy to double check.

I believe there's a performance reason on why bytes are chosen for external sorting and in particular how bytes get prefixed. 1) increases data locality on disk 2) there's no serde of every entry so we can compare.

In the `NativeSorter` case since it uses merge sort this solution is quite performant. 

To be humble not sure yet what the right solution is but i'm a bit skeptical of providing a custom implementation of `SortValues` and `NativeSorter` that allows more broader use cases and by consequence has drastic performance penalty. Perhaps, we should just steer the user to the right solution by having a stricter API?

**Comment by nevillelyh** [comment]
Yeah not sure if worth the effort to support everything. We can make the existing `SortValues` based approach super restrictive, e.g. only `String`, `Array[Byte]` & ascending order?
IMO people really should use `topByKey` most of the time.

**Comment by regadas** [comment]
I agree as well that most ppl should just use `topByKey` and that's why we should keep `sortValues` under `scio-extra`. Restricting and add better docs is what i had in mind.

I'll update #2542

**Comment by regadas** [comment]
Closed by #2542
