### ISSUE TITLE
SMB join immediately followed by write without re-shuffle

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2653]
There're cases we want to perform SMB join and then save immediately using the same key scheme without re-shuffle. For example when joining a large event stream with a small metadata stream both keyed on user, and save as an enriched event stream.

If we were to keep the source and sink APIs separate, we'll have to expose the underlying `Iterable<K, CoGbkResult>` to retain bucket unity & key ordering. Alternatively we can create a new end-to-end composite transform that allows a user defined `KV<K, CoGbkResult> -> KV<K, Iterable<VOut>>` function?

**Comment by ClaireMcGinty** [comment]
Hm, so we need a way to get the key-group results from the `SortedBucketSource#MergeBuckets`, transform them from `KV<K, CoGbkResult>` --> `KV<BucketShardId, Iterable<KV<byte[], V>>>`, and feed them directly into `SortedBucketSink#WriteOperation<VOut>` ? Seems like we would need a new composite transform that strings together these `DoFns` with a user-supplied function to transform `CoGbkResult` into an `Iterable<VOut>`. We might have to abstract out some of the `MergeBuckets` logic to make it reusable?

I do like the idea of some kind of `SmbDoFn` that operates directly on bucketed key-groups without reshuffling the elements but haven't fully thought it through yet.

**Comment by ClaireMcGinty** [comment]
I got a basic implementation of this working, where the user supplies a function mapping `KV<FinalKeyT, CoGbkResult> -> FinalValueT`. I combined the file writing logic with the MergeBuckets logic in the same DoFn: we read a key group, transform it into `FinalValueT`, and then immediately write it to its new destination. This also has the advantage that we don't have to materialize the entire `KV<BucketShardId, Iterable<FinalValueT>>` in memory since we're reading and writing one key group at a time. A few considerations:

- Sharding -- my implementation allows a user to supply a desired `numShards` then just opens `numShards` Writers per bucket and assigns key groups to them in round-robin style. Haven't tested this out on real Spotify datasets yet.
- BucketMetadata for the transformed source -- do we want the user to explicitly supply this or try to infer it from the input sources? We know `numBuckets`, user supplies `numShards`, we know `Class<FinalKeyT>` and `HashType`... the only thing we can't infer is `FinalKeyT extractKey(FinalValueT value)`. User may have to supply that, although we don't have a way to validate that it's correct. 🤔

**Comment by nevillelyh** [comment]
`KV<FinalKeyT, CoGbkResult> -> FinalValueT` function is 1-to-1 in-to-out mapping? Or is it more like a `DoFn` with `ProcessContext#output`? Asking because we probably want to avoid materializing output `Iterable<FinalValueT>`.

Sharding exists to prevent worker key skew, so there's little value in having > 1 shards now that we're bypassing shuffle? Like if the `CoGbkResult` for a key has heavy skew, that particular worker will strangle anyway.

For metadata, it's still possible to have different in/out formats, e.g. Avro -> TF, or even same Avro, different schema (`FileOperations`)? Not the end of the world if user has to copy paste the same impl & modify for in/out.

**Comment by ClaireMcGinty** [comment]
Right, `Iterable<FinalValueT>` is never materialized, we write each element as soon as it's transformed to `FinalValueT`.

I think sharding is also valuable to keep file size down--especially since the # of buckets written is going to match the smallest # of buckets amongst input sources.

**Comment by nevillelyh** [comment]
Fixed in #2693, #2704, #2712
