### ISSUE TITLE
Cache implicit resolution of Coders

### ISSUE THREAD

**Issue by jgogstad** [spotify/scio#2811]
Happy to move the conversion to https://github.com/spotify/scio/issues/1898, But as the original author closed it, I figured a new issue was in order. Please excuse the duplication, and feel free to close this if you would rather take the discussion elsewhere.

As the original ticket states, scio doesn't cache materialization of `Coder` instances. Any module with a non-trivial amount of scio code quickly takes more than a minute to compile, often several minutes.

> Coder instance derivation may be different in different implicit scopes

Yes, true, they can. But if you have multiple different ways of coding a type, and you're using the implicit scope to make that decision, you better rewrite your application logic. It is _far_ better for everyone to have great compilation speeds, than to cater for the odd case of multiple different representations of `Coder[A]` for some `A`.

I'd like to point out that this is highly uncontroversial, and it is the stance that libraries like circe takes; derivation of `Encoder`s and `Decoder`s are cached (relevant talk: Travis Brown's "Generic Derivation: The Hard Parts" at Scalaworld, [talk](https://www.youtube.com/watch?v=80h3hZidSeE), [slides](http://meta.plasm.us/slides/scalaworld/#1))

**Comment by jto** [comment]
Hi @jgogstad, 

While I do agree that slow compilation times are a problem, I do not wish to introduce changes in Scio that would break at runtime a job that was working properly with an older version. I am especially careful with `Coder` considering that serialization issues are quite hard to debug. 

I also don't think it is our role as OS library authors and maintainers to decide one should rewrite their application logic and will point out that the case of implicit resolution being dependent of the scope can easily arise when one uses Beam's `Row` or Avro's `GenericRecord` as those types could be members of a product type whose `Coder` is derived.

Could you be more explicit about the source of:
> this is highly uncontroversial, and it is the stance that libraries like circe takes; derivation of Encoders and Decoders are cached 

AFAIK, Circe does not cache derivation (at least for `auto` derivation provided by `circe-generic`). According to Travis, [it won't be supported](
https://gitter.im/circe/circe?at=5d7bb5a92e8fd94630c7699e) in the future because the implementation is "tricky".

If you have example of libraries that provide automatic derivation of instances and manages to cache it, please let us know, I'll happily look into it.

**Comment by jgogstad** [comment]
Thanks for a thorough answer

> I also don't think it is our role as OS library authors and maintainers to decide one should rewrite their application logic and will point out that the case of implicit resolution being dependent of the scope can easily arise when one uses Beam's Row or Avro's GenericRecord as those types could be members of a product type whose Coder is derived.

That's a fair point

> If you have example of libraries that provide automatic derivation of instances and manages to cache it, please let us know, I'll happily look into it.

I see I was imprecise and wrong, circe-generic indeed doesn't cache instances. I was thinking of https://github.com/circe/circe-derivation; it obtains speedup by using macros instead of implicit searches for deriving instances, so no cache.
