### ISSUE TITLE
Cancel Dataflow job on timeout?

### ISSUE THREAD

**Issue by labianchin** [spotify/scio#2813]
This looks like a regression on Scio 0.8: I think Scio 0.7.x had [some logic to cancel DF jobs](https://github.com/spotify/scio/blob/v0.7.4/scio-core/src/main/scala/com/spotify/scio/ScioResult.scala#L80) when timing out on `waitUntilDone()`/`waitUntilFinish()`.
It seems this behaviour is [no longer available on Scio 0.8.x](https://github.com/spotify/scio/blob/v0.8.3/scio-core/src/main/scala/com/spotify/scio/ScioResult.scala).

Not sure if intentional or not.

Still, when using Beam’s PipelineResult users can do something [like this](https://github.com/spotify/dbeam/blob/346e838087e8d5b67588071491e5956d243321fc/dbeam-core/src/main/java/com/spotify/dbeam/beam/BeamHelper.java#L43) to have the same behaviour.

**Comment by jto** [comment]
@labianchin Thanks for the report.

Scio directly [delegates](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L627) to Beam which seems to [return without canceling the job](https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineJob.java#L326).

I don't think it was intentional. (ping @regadas).
