### ISSUE TITLE
Create a separate module for `PubSubIO`

### ISSUE THREAD

**Issue by jto** [spotify/scio#3202]
Currently `PubSubIO` is part of `scio-core`. 

Because of this, `scio-core` pulls `beam-sdks-java-io-google-cloud-platform` which has a ton of dependencies (including all dependency conflicts usual suspects).

PubSub should like Bigquery, live in its own separated module.

**Comment by nevillelyh** [comment]
I also noticed this deprecation. https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala#L73

We can't really remove it because `ScioContext#pubsub*` and `SCollection#saveAsPubsub*` depend on this "generic/reflective" behavior. A proper fix would require adding specialized `ScioContext#pubsub{Avro,Proto,String,...}` and `SCollection#saveAsPubsub{Avro,Proto,String,...}` right?

**Comment by regadas** [comment]
Closed in favor of #3237
