### ISSUE TITLE
Support saveAsDynamic* for @AvroType-annotated classes

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#3341]
currently it seems to be supported only for [generic and specific Avro records](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/io/dynamic/syntax/SCollecionSyntax.scala).

**Comment by jasmineytchen** [comment]
I would like to pick up this issue :)

**Comment by jasmineytchen** [comment]
`saveAsDynamic*` support for generic and specific Avro records sit in `scio-core` atm. From what I see, to support @AvroType-annotated class we would need to bring in dependency from `scio-avro` module (I am thinking `@HasAvroAnnotation` specifically) if we were to keep the additional `saveAsDynamic*` in the same source file as generic / specific records. Otherwise, the `saveAsDynamic*` method for can be added to [here](https://github.com/spotify/scio/blob/master/scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala). Can you shed some light on this and suggest which approach is more suitable to support this use case?

**Comment by nevillelyh** [comment]
@ClaireMcGinty should we close this? Since we don't want to promote more `@AvroType` usage. It can be done with `GenericRecord` with magnolify or Scala 3 derivation instead.
