### ISSUE TITLE
ElasticsearchOptions type is a bit ambiguous

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3573]
We should rename this type to something like `ConnectionOptions`. If would be great if we could keep bin compat.

**Comment by shan-sahaj** [comment]
Hi @regadas , I would like to take up this issue if no one is working with it. I have made a clone and looked at the 
class. From whatever I see in this issue , the issue is that this class encapsulates only the connection parameters for ES and hence it should be be more correctly named as ConnectionOptions. It is already under package com.spotify.scio.ElasticSearch , so no point redundantly specify that in the name. After that you have added an additional req of encapsulating the username, password as well. Is that correct?

**Comment by shan-sahaj** [comment]
I would also like to get a clarity on why the version 6 and version 7 of this class encapsulate different attributes? The version 7 does not have the cluster-name but have the userName and password attributes. Can anyone explain the difference?

**Comment by RustedBones** [comment]
@regadas considering #4311 , we need to introduce a `JsonpMapper` factory in the `ElasticsearchOptions`, so the es client is able to serialize custom documents.
Is this issue still relevant since the options won't only contain connection info, or do we want to split those?
