### ISSUE TITLE
Use Java Low Level REST Client for Elasticsearch

### ISSUE THREAD

**Issue by mrkm4ntr** [spotify/scio#3575]
We use transport client for Elasticsearch 6 and  Java High Level REST Client for Elasticsearch 7. This is not good for maintenability.
According to [this](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-overview.html), Java Low Level REST Client is compatible with all Elasticsearch versions. If we use this, we can unify scio-elasticsearch6 and scio-elasticsearch7.
If this proposal is reasonable, I will create scio-ealsticsearch and remove 6 and 7.

**Comment by regadas** [comment]
The reason behind this separation is merely due to ES version evolution and underlying breaking changes that if users don't carefully manage their dependencies would cause issues.

Elasticsearch 6 is on it's way out (EOL) so we will remove in one of the next versions, not sure which one yet. That said, I don't think we should worry about this module and regarding #3572 we can actually skip changes here since it's EOL and there was no previous interest in supporting it.

**Comment by mrkm4ntr** [comment]
I see, thanks!
