### ISSUE TITLE
Build sbt file previousVersion function seems not correct 

### ISSUE THREAD

**Issue by ashwini-tgam** [spotify/scio#3889]
Do this previous version function will create issues if we have any version values as 1.3 ?
https://github.com/spotify/scio/blob/main/build.sbt
`
def previousVersion(currentVersion: String): Option[String] = {
  val Version = """(\d+)\.(\d+)\.(\d+).*""".r
  val Version(x, y, z) = currentVersion
  if (z == "0") None else Some(s"$x.$y.${z.toInt - 1}")
}
`

If i give previousVersion("1.2") it will error for sure so is this expected?

**Comment by RustedBones** [comment]
Previous version is meant to be used in the [MiMa](https://github.com/lightbend/mima) settings.
This is actually used to make sure that PATCH releases (We follow [SemVer](https://semver.org)) does not break binary compatibility with previous version.

- `1.3` does not follow semantic versioning, so this is not a valid use case
- New MAJOR or MINOR releases like `2.0.0` will not return a  `previousVersion`, because there is no artifact to check compatibility against
