### ISSUE TITLE
SCollection's sort()

### ISSUE THREAD

**Issue by ChandruDW** [spotify/scio#4264]
Is there a way to sort SCollection by key or value?

**Comment by ChandruDW** [comment]
Also for reverse() in SCollection

**Comment by mioalter** [comment]
An `SCollection` is a distributed list of data so to sort it you would have to force all the data onto one machine. You can do that, but you probably don't want to.

**Comment by ChandruDW** [comment]
But spark's RDD has sortByKey, so when scio supports beam(which inturn support Spark), so I expect scio should have that function. Please correct me if I am wrong

**Comment by anish749** [comment]
Spark's RDD does have a notion of global ordering since it exposes partitions as a user facing api, and each partition has an index, hence global ordering on a distributed collection is achieved by ordering the partitions first, and then ordering the data in each partition ensuring that the ranges in each partition are in order.

Beam (and hence Scio) doesn't have a concept of a partition, and hence it doesn't have a notion of global ordering of a distributed collection.
