### ISSUE TITLE
NPE on 0.12.0 SNAPSHOT when setting gcpTempLocation

### ISSUE THREAD

**Issue by turb** [spotify/scio#4535]
We use gcpTempLocation to locate the temp directory in the same region than runners. The parameter is set like this: `--gcpTempLocation=gs://our_bucket_in_the_right_region/temp`.

When trying 0.12.0 (last one being 0.12.0-RC2+1-e8854f73-SNAPSHOT), I get an NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at org.apache.beam.sdk.io.FileSystems.parseScheme(FileSystems.java:501)
	at org.apache.beam.sdk.io.FileSystems.matchNewResource(FileSystems.java:587)
	at com.spotify.scio.util.ScioUtil$$anonfun$tempDirOrDefault$2.apply(ScioUtil.scala:121)
	at com.spotify.scio.util.ScioUtil$$anonfun$tempDirOrDefault$2.apply(ScioUtil.scala:119)
	at scala.Option.getOrElse(Option.scala:201)
	at com.spotify.scio.util.ScioUtil$.tempDirOrDefault(ScioUtil.scala:119)
	at com.spotify.scio.io.TextIO.write(TextIO.scala:93)
	<snip>
```

Looks like `ScioUtil` has been changed in @kellen's PR #4461 a few days ago but I don't see how the `tempDirOrDefault` function has been affected.

**Comment by kellen** [comment]
The command-line option may be null here: https://github.com/spotify/scio/blob/main/scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala#L120

I _think_ the best path forward would be to (1) not NPE (2) additionally check `gcpTempLocation` if that's set (3) throw an IllegalArgumentException if none of these are available. cc: @clairemcginty

**Comment by turb** [comment]
@kellen that's precisely what PR #4536 is doing ;)

**Comment by clairemcginty** [comment]
I don't know if the best remediation is to use gcpTempLocation as a default -- it's basically the opposite behavior to what Beam does, which is to use `--tempLocation` as a default option if `gcpTempLocation` isn't set ([source](https://github.com/apache/beam/blob/master/sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcpOptions.java#L316)) 🤔 

IMO it would be more "correct" to have `tempDirOrDefault` return an `Option[ResourceId]` that's `None` if `sc.getTempLocation` is not set... and in that case, writes would just not set a tempLocation. Like instead of writes like [this](https://github.com/spotify/scio/blob/7f229ea74bba2e94c1a4a9e51a5efe4940cae2f6/scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala#L356-L361):

```scala
      val transform = write
        .to(fp)
        .withTempDirectory(tempDirectory)
        .withNumShards(numShards)
        .withCodec(codec)
        .withMetadata(metadata.asJava)
```

It would be:

```scala
var transform = write
        .to(fp)
        .withNumShards(numShards)
        .withCodec(codec)
        .withMetadata(metadata.asJava)
transform = tempDirectory.fold(transform)(transform.withTempDirectory)
```

Not only would this fix the above bug but I think it would prevent a regression in temp-directory behavior: previously, if a user didn't supply a `--tempLocation`, the runner would infer one for the filesystem. By essentially forcing users to set a temp location we're removing runner's ability to infer it.

Wdyt?

**Comment by clairemcginty** [comment]
@turb , can we get a little more context on:

1) what runner you're using
2) are you also supplying a `--tempLocation` param or leaving it blank?
3) a snippet of your Scio job code that led to this error (prob a `.saveAsTextFile` call)?

Thanks! I just tested a sample job with no `--tempLocation` or `--gcpTempLocation` set, using DataflowRunner, and found that Dataflow at least, will infer a sensible default value for `tempLocation` by the time FilenamePolicySupplier#resolve is called. So I want to understand your setup a bit more!

**Comment by turb** [comment]
My command includes: `--runner=DataflowRunner --region=europe-west1 --stagingLocation=gs://bucket-name/staging --gcpTempLocation=gs://bucket-name/temp`. `stagingLocation` may be the trigger parameter.

Indeed, it fails on a `.saveAsTextFile("gs://another-bucket/target/dir")`

It works well with scio 0.11.10.
