### ISSUE TITLE
Generic types in Sparkey side input

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#473]
Right now `SparkeySideInput` only works with strings. Performance could be much better if we support generic types by allowing users to provide a custom byte array ser/de for their objects. Have an initial idea here: https://github.com/andrewsmartin/sparkey-scala

Any thoughts / reasons not to do this?

**Comment by andrewsmartin** [comment]
@rgruener fyi

**Comment by nevillelyh** [comment]
Sparkey only supports `String` key and `String` or bytes value right? Most Sparkey files we have are built in Python so strings only. Not sure if this will add a lot of value.

**Comment by andrewsmartin** [comment]
It also supports bytes for the key, which I think would be useful for ids and stuff.

**Comment by nevillelyh** [comment]
Bytes don't compare properly and could lead to bugs. I prefer leaving this to user land if they really want it and understand the consequences.

**Comment by rgruener** [comment]
Both key and values are simply stored as bytes with sparkey and we do use that quite a bit to store hex ids as longs in order to save much needed space. Perhaps the best thing to do would be to provide [this implicit ](https://github.com/spotify/scio/blob/apache-beam/scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala#L98) as (Array[Byte], Array[Byte]) in addition to the (String, String) to allow for us to do conversions ourselves.

I should mention we are definitely more interested in using the `asSparkey` method to make a sparkey available in GCS to be downloaded in our backends so having that be flexible for things other than for use as side inputs is definitely important.

**Comment by ravwojdyla** [comment]
I would be -1 to exposing `Array[Byte]` interface, as @nevillelyh said before, arrays can can be dangerous. One thing about arrays is that they don't have sensible `equals` and `hashCode`. One solution could be to use `Bytes`. Another solution might be to expose `Bytes` API + take implicit bijection from `T -> Bytes`?

**Comment by rgruener** [comment]
Yeah, agreed that Array[Byte] is not necessary. I like the idea of the `Bytes` and bijection.

**Comment by andrewsmartin** [comment]
We can get the wanted performance improvements simply by allowing `Array[Byte]` I/O, without getting fancy with type conversions. The user can convert to `Array[Byte]` if they want to do so. This is enabled in https://github.com/spotify/scio/pull/483

**Comment by nevillelyh** [comment]
Can we close for now?

**Comment by andrewsmartin** [comment]
Sounds good to me 👍
