### ISSUE TITLE
Make Scio BOM plugin

### ISSUE THREAD

**Issue by kellen** [spotify/scio#4896]
With no current BOM support in sbt, the recommended way to ship a set of dependencies (see sbt/sbt#4531) is via a plugin.

This wouldn't have quite the same semantics as a BOM, but would simplify keeping dependencies in sync for users (both internal and external)

**Comment by RustedBones** [comment]
since scio 0.14.6, a BOM is `scio-bom` artifact is published. When used with `beam-bom`, `netty-bom`, gcp `libraries-bom` ...
User can override with the expected versiom.

It would be convenient to build a sbt plugin, depending on [here-sbt-bom](https://github.com/heremaps/here-sbt-bom) to do this by default
