### ISSUE TITLE
ScioContext.close() incompatible with DataflowTemplateJob

### ISSUE THREAD

**Issue by jobegrabber** [spotify/scio#527]
If you run a `DataflowTemplateJob`, i.e. run a pipeline on Dataflow and `setTemplateLocation`, calling `close()` on the `ScioContext`  will throw an `UnsupportedOperationException`: `The result of template creation should not be used.`.

From the stacktrace I infer this is because the `ScioResult` [that gets built](https://github.com/spotify/scio/blob/v0.3.0-beta3/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L341) queries the pipeline's inner state [here](https://github.com/spotify/scio/blob/v0.3.0-beta3/scio-core/src/main/scala/com/spotify/scio/ScioResult.scala#L96) - `DataflowTemplateJob.getState()` will then [throw aforementioned Exception](https://github.com/apache/beam/blob/v0.6.0/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/DataflowTemplateJob.java#L67). 

This was observed on Scio 0.3.0 Beta 2, though I don't see anything that's different to Beta 3 in this regard.

**Comment by nevillelyh** [comment]
Thanks for reporting. Can you paste some minimal snippet of template job usage please?

**Comment by jobegrabber** [comment]
```
def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)
    SetupDataflowJob(sc)

    sc.customInput("ConsumeFromKafka", kafkaReader)
      .withName("DropKeys").map { _.getValue }
      // Some parsing and filtering
      .withName("CreateBigtableMutations").createBigtableMutations
      .saveAsBigtable()

    sc.close()
  }

def SetupDataflowJob(sc: ScioContext) = {
    val opts = sc.optionsAs[DataflowPipelineOptions]
    opts setRunner classOf[DataflowRunner]

    opts setTemplateLocation config("dataflow.template-location")
    // Some other options set (numWorkers, machineType etc.)
    opts setStreaming true
  }
```

Will throw:
```
Dataflow SDK version: 0.6.0
java.lang.UnsupportedOperationException: The result of template creation should not be used.
        at org.apache.beam.runners.dataflow.util.DataflowTemplateJob.getState(DataflowTemplateJob.java:68)
        at com.spotify.scio.ScioResult.state(ScioResult.scala:96)
        at com.spotify.scio.ScioResult$$anonfun$1.applyOrElse(ScioResult.scala:69)
        at com.spotify.scio.ScioResult$$anonfun$1.applyOrElse(ScioResult.scala:68)
        at scala.concurrent.Future$$anonfun$onFailure$1.apply(Future.scala:138)
        at scala.concurrent.Future$$anonfun$onFailure$1.apply(Future.scala:136)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I'm currently trying to reproduce this with the WordCount example, will update later today.

**Comment by jobegrabber** [comment]
With 0.3.0 Beta 3 (a3831f3) and
```
sbt "scio-examples/run-main com.spotify.scio.examples.WordCount --output=gs://${BUCKET_OUT} --runner=DataflowRunner --templateLocation=gs://${BUCKET_TEMPL}" 
```
you will get the same Exception.

**Comment by andrewsmartin** [comment]
So it seems like there's two things going on - one is that querying the internal `State` is not supported during the creation of template jobs (since it's not really a "pipeline") - internally we can handle this either by not querying the state during template creation jobs (via `.isInstanceOf[DataflowTemplateJob]`), or just silently using `State.UNKNOWN` for any failure case, which should be OK since I don't think orchestration really makes sense for template creation anyway. @nevillelyh @ravwojdyla thoughts on this?

The other issue which comes up when running the `WordCount` example, which is that this example tries to print out accumulators, which I'd consider undefined for a template creation job. If you run the `MinimalWordCount` example (which does not use accumulators), even though the `UnsupportedOperationException` comes up in the logs, the template does get created and everything should work despite the error message.

@jobegrabber It looks like your job is not using accumulators so based on what I've tested so far, it seems like the template creation should work even though you get the error message - can you confirm this?

**Comment by andrewsmartin** [comment]
#530 should get rid of the error message.

**Comment by jobegrabber** [comment]
@andrewsmartin Yes, the template creation still happens and Dataflow Jobs based on the resulting template start up without any problems.

I think #530 is just the right solution to this issue.
I actually tried to put up a pull request containing that change, though I had issues setting up and building the source code in IntelliJ IDEA. What IDE are you using, any additional plugins?

**Comment by andrewsmartin** [comment]
Thanks for your interest in contributing! Most of us internally use IntelliJ with the Scala plugin, along with [this plugin](https://github.com/spotify/scio-idea-plugin) so that the IDE works with the type-safe BigQuery API. Even without it though, you should still be able to build and run directly through sbt in the shell. Feel free to join us in the Gitter chat if you want some help setting up your environment in the future!
