### ISSUE TITLE
[0.3.0] Duplicate classes when generating a fat-jar

### ISSUE THREAD

**Issue by ElPicador** [spotify/scio#534]
We generate a fat jar with `sbt assembly`, and there is at one duplicate file `com.google.cloud.dataflow.sdk.util.BigQueryTableRowIterator` present in 2 dependencies, and with a different content:

* `scio-bigquery`
* `org.apache.beam:beam-sdks-java-io-google-cloud-platform:0.6.0`

I'm not sure which version to keep. 

This issue prevent us to migrate to beam, test scio 0.3.0 and reduce our $$$ usage (a bug is fixed in beam).

**Comment by nevillelyh** [comment]
Yes we monkey patched [BigQueryTableRowIterator](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTableRowIterator.java) in Beam since the upstream one is package private and we need it to iterator through BQ rows locally.

Shouldn't which one if you're not using BQ in REPL or `BigQueryClient` directly. Otherwise keep the one in `scio-bigquery`.

BTW we use sbt-docker instead of assembly jar. That saves us the hassling dealing with merge strategies and upload is faster since most dependencies can be cached.

**Comment by ElPicador** [comment]
Thanks for the quick answer, and for `sbt-docker`.

👍

**Comment by ravwojdyla** [comment]
@ElPicador `sbt-docker` is good if you want docker. Alternative to `sbt-assembly` is [`sbt-pack`](https://github.com/xerial/sbt-pack) (which we use), the advantage of using `sbt-pack` over assembly for scio/beam:
 * no assembly strategies to worry about
 * caching of dependencies works better and faster because, after a change in your pipeline you only need to upload a small "pipeline jar" only, all the other dependency jars are cached in staging bucket

**Comment by ElPicador** [comment]
thanks @ravwojdyla, I'll try them!
And no more assembly strategies and exclusions
