### ISSUE TITLE
Using @BigQueryType.toTable annotation results in cryptic error messages when the companion object already exists.

### ISSUE THREAD

**Issue by justjoheinz** [spotify/scio#665]
Doing something like

```
@BigQueryType.toTable
case class Foo(bar: String, moo: Int)

case object Foo {
  def validate(bar: String: moo: Int) : Option[Foo]
}
```

results in a very cryptic compile time error, because the macro does not expect that the companion object already exists.
This should be fixed, and eventually the wiki page about typed big query queries amended, that it is not allowed to provide a custom companion object.
Ideally the macro should be more stable and just add to the existing companion object.

**Comment by nevillelyh** [comment]
Thanks for reporting. It's hard to fix this in macro though, due to 2 reasons I can think of.

- `case class Foo` is the only type annotated and visible by the macro while `case object Foo` is not, so it's hard to modify the companion object.
- Macro expansion happens before compilation and since `case object Foo` is not visible it's hard to detect duplicates.

I need to toy with some ideas but for now documentation maybe be the easiest solution.

**Comment by justjoheinz** [comment]
Maybe a better approach would be to declare a HelperClass which contains the methods which are to be generated. A little bit like for play-json.

```
case class MyFoo(....)

case object MyFoo {
  def myFn(....) = ??? 

  val helper : ScioHelper[MyFoo] = ScioMacro.generate[MyFoo]

  val schemaAsString: String = helper.toPrettyString(2)
}
```

Of course this would break compatibility, but AFAIK would improve IDE support. For some reason, the Intellj plugin does not work for me BTW.

**Comment by nevillelyh** [comment]
Did you mean this plugin? https://github.com/spotify/scio-idea-plugin/
Could you file an issue there please?

**Comment by ravwojdyla** [comment]
fyi - issue at spotify/scio-idea-plugin/issues/7

**Comment by nevillelyh** [comment]
Added a comment here https://github.com/spotify/scio/wiki/Type-Safe-BigQuery#companion-objects
I don't see a way to handle this properly right now. Will close for now. Feel free to reopen if anyone has better ideas :)
