### ISSUE TITLE
Properly wrap Beam coders instead of relying on Kryo

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#827]
I want to revisit something that came up in #476 (and seems relevant again - see #825). With `KryoAtomicCoder` we ended up, for example, adding code to mimic the behavior of `IterableLikeCoder` so it can properly handle large elements but we incurred a performance penalty too (#825). While it's awesome that we have Kryo to fall back on I think we can prevent performance issues and other things that come up by minimizing our dependence on Kryo - which means properly wrapping the Beam coders for common types - and treating `KryoAtomicCoder` as the last resort it was meant to be.

**Comment by kanterov** [comment]
Agree, also it worth to use specialized coder when saving objects to files. Our current serialization format is suited for both cases. It's suboptimal solution for shuffling, getting rid of `VarInt(-1)` header and chunks will improve a performance of encoding by extra 10%, as well as it's a significant part of the payload for small keys.

**Comment by andrewsmartin** [comment]
Yep agree, it's especially problematic with small keys which I think are seen very often.

**Comment by andrewsmartin** [comment]
Thinking about this a bit more - how bad would it be to just remove `KryoAtomicCoder` altogether? It would suck to force users to define coders for their custom types, but `KryoAtomicCoder` completely breaks coder inference and could cause essentially the same problems we've seen in the past (out of memory errors / bad performance) and any future problems from over-generalizing `KryoCoder` to do everything.

Maybe a good approach would be to keep Kryo for the convenience, but somehow emit a warning when it is actually needed due to lack of custom coder. Thoughts?

**Comment by kanterov** [comment]
@andrewsmartin When I was building a prototype, I used the same approach as in github.com/typelevel/frameless, instead of `ClassTag` operations on `SCollection` require implicit `KCoder`. `KCoder` is typeclass that can encode Scala objects to/from a byte stream. It has few implicits with different priorities – specialized instances from Beam, as well as an implicit macro for case classes with lower priority.

This approach is superior to reflection because it can handle type erasure properly – there is no type information for `List[X]` in runtime, but Scala compiler can use right implicit. Problem with Kryo that it would include class ids for each element in the list, even if we statically know that they all have the exact type. 

Overall, this approach is better because:
- has a potential for better performance
- allows users to specialize and easily control how things are serialized in idiomatic to Scala way
- guarantees that things are serializable at compile time

This way we can optimize the size of serialized objects, that would be awesome when Dataflow will support external shuffle service. The problem that this requires changing a significant part of the codebase, as well as completely breaking API.

**Comment by nevillelyh** [comment]
I played around with this idea with shapeless type class companion too. But there're some downsides.
- Conversion to HList and back adds overhead, not sure how that compares to Kryo
- It adds signification compilation time and make it hard to debug when implicits are not found

IMO significant code change and breaking API is less of a adoption blocker than the above issues.

The macro approach should be faster to compile but less flexible and harder to maintain?

**Comment by kanterov** [comment]
I agree plain shapeless doesn't satisfy performance requirements. In frameless [shapeless is used to generate Java code](https://www.youtube.com/watch?v=SYAxLwd11Qo), not to derive typeclass instances by composing functions. It should be possible to use this approach with Dataflow cloud objects, however, just macro should be easier and faster.

There is a challenge in combining macro with implicits, however, there are projects like [circe-derivation](https://github.com/circe/circe-derivation) that utilize this approach.

**Comment by kanterov** [comment]
We can provide an implicit macro for case classes, however, it doesn't prevent users from using shapeless, if performance isn't the main concern.

**Comment by kanterov** [comment]
One of the things to consider is using `scala-lms` for runtime code generation instead of the approach that is taken in Spark.

**Comment by nevillelyh** [comment]
Closing this as it's way too ambitious. Save for a later time.

**Comment by kyprifog** [comment]
@kanterov I was wondering about frameless analogue to TypedDataset for scio SCollection today and stumbled on this thread.  Enjoyed reading   Since its been 4 years, i'm curious if you know if anything in these areas has evolved in scio since then.
