### ISSUE TITLE
Define custom PipelineOptions

### ISSUE THREAD

**Issue by labianchin** [spotify/scio#837]
Is there a plan to support/define custom `PipelineOptions` (https://beam.apache.org/documentation/programming-guide/#options)
in a friendly/scala way? 

The [`ContextAndArgs.parseArguments`](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L68) call splits into `args` and `pipelineOpts`. That makes handling arguments from `args` a bit unsafe. Also many times it is necessary to pass `(sc, args)` around. 

It would be interesting to have type safe arguments and accessible in the `ScioContext`.

This is more of a question about a "subjective" problem.

**Comment by ravwojdyla** [comment]
Currently there is no issue/plan open for this; as you know you can still perfectly fine use the `PipelineOptions` mechanism from Beam in Scio. I'm leaning more towards just keeping it the way it is right now, just so that there is only "one" familiar and easy way to handle arguments, while at the same time users are free to use the `PipelineOptions` if they want/need to.

**Comment by nevillelyh** [comment]
:+1: on keeping it as is. The user can still do `val (sc, _) = ContextAndArgs.parseArguments[CustomOptions]` and discard the unsafe arguments (or assert it's empty?).

**Comment by ravwojdyla** [comment]
Closing for now.

**Comment by labianchin** [comment]
Thanks!

A related question: would it make sense to have `args` as a member part of the `ScioContext`? That would avoid to pass `args` everywhere. I can share some internal examples.

**Comment by ravwojdyla** [comment]
@labianchin I would prefer not to do that, mostly because `ScioContext` already knows a lot, adding more smells like a god class; having a god object would also lead to it being passed around without clear intent. Also if `args` were to be stored in `ScioContext` it might lead to serialization issues if used directly in a lambda (given that `ScioContext` is not serializable).

If you don't want to pass `args` around, you can always make `args` an implicit argument to your methods, and make `implicit val (sc, args) = ContextAndArgs(cmdlineArgs)`, I think it's a big overkill, but it's an option.

**Comment by labianchin** [comment]
I see that makes sense. Thanks for clarification! I will look at both implicit arguments and pipeline options.
