### ISSUE TITLE
parquet read can NPE on chained attributes

### ISSUE THREAD

**Issue by pdeglopper** [spotify/scio#928]
When attempting to project parquet records to just certain nested fields (eg `Projection[SomeType](_.getFoo.getBar)` I saw many NPEs apparently from serializing the records while trying to read them. Switching to just projecting the top-level field (`_.getFoo`) got past it.

**Comment by nevillelyh** [comment]
https://github.com/spotify/scio/blob/master/scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/package.scala#L102

`.map(_.getValue)` returns an incomplete Avro object which fails serialization. We need to trick the runner/coder somehow to ignore these, since they're almost always mapped out to leaf fields.
